In [1]:
import numpy as np
import numpy 
from numpy import *

In [4]:
my_vector = np.array([2,3,4])

my_vector.shape #(3, )
my_vector_col = my_vector.reshape(-1,1) #Vector columna (3,1)
my_vector_fila = my_vector.reshape(1,-1) #Vector Fila (1,3)

In [15]:
my_vector_fila + my_vector_fila

array([[4, 6, 8]])

In [16]:
my_vector_fila*3

array([[ 6,  9, 12]])

In [21]:
np.dot(my_vector_fila,my_vector_col) # Dot Product, producto interno

array([[29]])

In [23]:
np.dot(my_vector_col, my_vector_fila) # Outer Product

array([[ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16]])

In [9]:
A = np.array([[3,4],
              [3,6]])
A.shape

(2, 2)

In [28]:
np.linalg.eig(A) #Eigenvalues
np.linalg.det(A) #Determinante
np.linalg.norm(A) # Producto Interno consigo mismo

8.366600265340756

In [30]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

## Arrays Aleatorios 

In [15]:
x = np.random.uniform(low=-1, high=3, size=(3,5))
x 

array([[0.67851444, 3.54357155, 1.98550199, 1.97145458, 0.50421183],
       [2.47746519, 2.78723455, 1.5688391 , 2.38166798, 2.89861912],
       [0.07722209, 2.48118119, 2.49966741, 2.35144851, 0.14475649]])

In [11]:
#subselección x[filas, columnas]
x[0,0] #i=0, j=0 

x[:, 0] #primer columna
x[0, :] #primer fila


array([ 0.18458079, -0.05250261, -0.8731138 ,  0.85598228,  1.91178631])

In [41]:
np.sum(x)
np.std(x)

1.1877416735754267

In [12]:
np.sum(x, axis=1)
np.std(x, axis=1)

array([0.93437226, 0.67530366, 0.9808166 ])

In [14]:
#Filtrar datos
x[x>2]

array([2.0667578 , 2.23087442])

## Ejercicios  

1. Crea una vector con 1000 normales y calcula el promedio y el desvío estándar

2. Suponé que tenes el siguiente sistema de ecuaciones:

In [53]:
A  = np.array([[2,4],[6,8]]) 
Y   = np.array([3,5]).reshape(-1,1)

El objetivo es encontrar el vector X, tal que  A@X = Y